### ISSUE TITLE
Doesn't work with local files

### ISSUE THREAD

**Issue by lazka** [sphinx-contrib/video#1]
The video files don't get copied to the build dir so all URLs are wrong in the end.

**Comment by cbscribe** [comment]
I'm having the same problem.

**Comment by dependent-type** [comment]
After cloning sphinxcontrib-video and then doing `pip install .` inside the cloned repository, I changed the `conf.py`
to say

```python
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.video'
]
```

I put `video.webm` in the`_static` subdirectory
(a sister to the `_build` directory and `conf.py`)
and then in some .rst file did this:

```rst

*****
title
*****

Here is a video

.. video:: _static/video.webm

```

```bash
build html
```

Then with some browser do:

```
open _build/html/index.html
```

It seems that any video in `_static` gets copied to `_build/html/_static`
