### ISSUE TITLE
Support for "loop" attribute is missing

### ISSUE THREAD

**Issue by avarga** [sphinx-contrib/video#3]
Currently there seems to be no way to control that the video should loop or not.

Looking into the code, looks like it currently supports the width, height, path, alt, autoplay and (no)controls HTML attributes. How about supporting more, like: loop, audio, poster, preload (see spec at https://www.w3.org/TR/2011/WD-html5-20110113/video.html#video)

I can provide a pull request if that helps.

**Comment by JulianGro** [comment]
#4
