### ISSUE TITLE
How to set width to "100%"?

### ISSUE THREAD

**Issue by Guts** [sphinx-contrib/video#41]
Hello,

Thanks for your extension.

This following code (I'm using markdown + MyST Parser) is not working:

````markdown
```{eval-rst}
.. video:: ../_static/qdt_assisted_edition_vscode.webm
  :alt: Your browser does not support HTML 5 video tag.
  :nocontrols:
  :preload: metadata
  :width: 100%
````

**Comment by andreasciamanna** [comment]
You can achieve this by adding the following to the custom CSS file:

```
video {
    max-width: 100%;
}
```

(I prefer using `max-width`)

You can narrow the scope with the `:class:` attribute, of course.

**Comment by Guts** [comment]
Thanks you!
