### ISSUE TITLE
ogv video gets wrong type tag 

### ISSUE THREAD

**Issue by fjansson** [sphinx-contrib/video#6]
Embedding an ogv video doesn't work for me.  In the html it gets the type tag video/ogv : `<source src="_static/video.ogv" type="video/ogv">`. What works for me (using Firefox) is changing the type to video/ogg: `<source src="_static/video.ogv" type="video/ogg">`

I can change the extension of the file to `ogg`, and then it should work, because type is determined from the file extension. But ogv is an acceptable extension, and the mime type should still be ogg.

**Comment by YariKartoshe4ka** [comment]
The same with *.mov* extension, which not supported by browser (i using Firefox too). I changed fileformat to *.mp4*, but it will be cool if there are able some option to redefine type in HTML video tag
